services:
  server:
    build:
      context: ./
      dockerfile: ./dockerfiles/apache.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html

  # *********** MySQL ***********
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
